version:
  name: velociraptor
  version: 0.75.1
  commit: 46ff090b9
  build_time: "2025-09-03T16:04:11Z"
  compiler: go1.23.2
  system: windows
  architecture: amd64
Client:
  server_urls:
  - https://localhost:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQTr4qni90UphenK5zUwsDTTANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwMjA1MDg1NjU5WhcNMzYw
    MjAzMDg1NjU5WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDSeGN8bXzPK4aIPA0fjETHe561H+oxl574
    /42JUjE5Da4CbIp574UN4WI0DI3Nb4Pp+pqIm3S+/BamUoLePBp9pcizAti4WR1d
    UCX1p1YYR+KX4Y1Q8mZLCL6Wc+pnJx19o3+m957OI/rxzJkpZFnwb9HsZEbqPus+
    1N2D+nHSE94zpU0mJTdMvE+dmM3Od6NJIwvm5CEABH73ThFCtse2y29B+FLyMS6r
    oPe3jg8fOlvEl2HSbmzDf5LSEYEYywLnBx+uzAzNiUecK4Mf39B94UEIFgGbO6Qx
    rwKyVAYmQczK16OJvc8HnJSdQqvUgN/KuqnIrEnialHiUTsOLNgjAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSdNc7IHCxjqoxnIpoJmNcrXB4G
    tTAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEApIXcUHXdTf5RzF8urrlM9/ikYRRtD4lWK4KTVxDSEEax
    hG6q6ZYRDtGuh2NKAypiuRktdrHfWNb624fizmQf+suBzNR6DoNtsDkduINuDq4y
    UG/uprSHtrVnzEWEdiJUFGDYD8svzTIqRL0NxoMgNt3VO//MKI78uVpcJDzARFqn
    NhXwgdtQTkH/DsLDtOvrk+dYP8TzQv0hrZB5R07Xs3GDweRvWWSYlIAs9lWz1Ouu
    Y8Uk0sGYnEQeBt3adnUDIOwmM49cy16UcqJemqURzQ7ChnWwNCi0VbpD67QU0lmc
    2usde0mBBTFkVwdqM9KwpX0cQ7jsZt0xt7RqbUAi7Q==
    -----END CERTIFICATE-----
  nonce: k+b/LrZ1KiU=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.75.1
    commit: 46ff090b9
    build_time: "2025-09-03T16:04:11Z"
    compiler: go1.23.2
    system: windows
    architecture: amd64
  server_version:
    version: 0.75.1
    commit: 46ff090b9
    build_time: "2025-09-03T16:04:11Z"
  use_self_signed_ssl: true
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
