version:
  name: velociraptor
  version: 0.75.1
  commit: 46ff090b9
  build_time: "2025-09-03T16:04:11Z"
  compiler: go1.23.2
  system: windows
  architecture: amd64
Client:
  server_urls:
  - https://xl1.ddns.net:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQH16FUtgXDfUJhE424w0qqDANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwMjA2MDMzODAyWhcNMzYw
    MjA0MDMzODAyWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDRvwZrmMe5RPB3rm7UAPU7AzRPVLYY3vK4
    YgifBNSLXwrQQpLcCH3BAkCSNsgsV8NIAzPx/e8R6UAg0441ketRl3sI8bjNTbSq
    51ZtWVtlp8RhNdl/n6Oi0cj0mFIKAvRTGcLDTpNC7ei57a74HvJVqgaBR+MG6JUo
    GOMdvnCgGstH2DyTrJSEQL8gbF+Bt+7FrFPrhB63eLrlUcH38CQGvbK3yEbui0nU
    Z/YOKlq1LNlpkvYSrscVh4JrANzHDeYFajPxsxi29+d9upxqc2mTXr75aavcdfnt
    S/11AtCvpJeWBQ9P0YTrIFY2F4YIWad9TqVm1sptrUtNoWbBgCRNAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQfuS+Fhy2s8uQpkgCFvBdDJkuw
    hDAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAG39NMLCaC0RPrpTlG9fXTE4+webeTT1a0pzoDqoMfpTx
    IdcI5/6V0tGqP3Wvtg2ov/KiLpuF7uT5CBefNF7HkxJF1QuNtHswuAITk5U61nlv
    hHxoDzAgJ82R1x4te48bU8uAewc9kLv/TM1hDt3WQIr3x1pyCcZoDVkCPPW+OuBo
    pmb0YH8veEV1nGLaV1EMs39BMV9GI7jeX6cIjw6ZST7CIen3tqxbNDJ0ldv+/ny0
    V1QWSnM6CBpxX+IOTKxxGhar1cfeaMGziGGBOdHq+SZRdzHqfbudW1M0g+2HEVtF
    9ejxre8TnvHQ2oRBLQkYuhc9vrkyeykQMEkxCDyeZg==
    -----END CERTIFICATE-----
  nonce: 2LppuVlmWZQ=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.75.1
    commit: 46ff090b9
    build_time: "2025-09-03T16:04:11Z"
    compiler: go1.23.2
    system: windows
    architecture: amd64
  server_version:
    version: 0.75.1
    commit: 46ff090b9
    build_time: "2025-09-03T16:04:11Z"
  use_self_signed_ssl: true
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
[ERROR] 2026-02-06T11:46:47+08:00 DynDns: Unable to set dns: Get "https://dynupdate.no-ip.com/nic/update?hostname=xl1.ddns.net&myip=2001:8004:51d0:3d5a:380e:9788:50f8:cc6b": context canceled 
